sudo: required
language: node_js
arch:
  - amd64
  - arm64  # please note arm64-graviton2 requires explicit virt: [lxd|vm] tag so it's recommended for jobs.include, see below
  - ppc64le
services:
  - docker
install: skip
script:
  - bash build_docker.sh