version: "3"
services:
  qinglong-xdd:
    image: tonglin138/qinglong_xdd:latest
    container_name: qinglong-xdd
    restart: unless-stopped
    tty: true
    ports:
      - 5700:5700
      - 8080:8080
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
      - XDD_REPO_URL=https://ghproxy.com/https://github.com/cdle/xdd
    volumes:
      - ./config:/ql/config
      - ./db:/ql/db
      - ./xdd:/ql/xdd